### ISSUE TITLE
Doesn't seem to work with stateless components

### ISSUE THREAD

**Issue by davidblurton** [pzavolinsky/react-ghost-i18n#1]
I'd like to use this but I can't get it to work with the stateless components added in React 0.14

**Comment by pzavolinsky** [comment]
Hi @davidblurton thanks for pointing this out. 

I've fixed compatibility with React 0.14 see [Stateless function components](https://github.com/pzavolinsky/react-ghost-i18n#stateless-function-components) and also updated the [demo](http://pzavolinsky.github.io/react-ghost-i18n/) to include some examples of this.

Unfortunately is not as magical as I would like but should work nevertheless.

Cheers!

**Comment by davidblurton** [comment]
Very nice! Thanks for the speedy fix.
